name: app_control_informes
description: Offline-first Android app for generator maintenance reports.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.1
  printing: ^5.13.4
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/templates/Formulario_base.pdf


flutter_launcher_icons:
  android: true
  image_path: "assets/branding/TecnoReport.png"
  min_sdk_android: 21

